### ISSUE TITLE
Error: Cannot find module '../dist/cli/initializeCLI'

### ISSUE THREAD

**Issue by vova3379** [magento/baler#29]
Hello, 

can someone suggest where i can find initializeCLI
this file and dist directory inluded in barel 

root@vmi223508:~/baler# tail -1 bin/baler
require('../dist/cli/initializeCLI').initializeCLI(process.argv, process.cwd());

but dist directory does not exist 

root@vmi223508:~/baler# ls
bin  docs  jest.config.js  node_modules  package.json  package-lock.json  prettier.config.js  prettier-globs  README.md  src  tsconfig.json

due to this barel produce error below 

root@vmi223508:~/baler# node -v
v12.13.1
root@vmi223508:~/baler# baler -v
Error: Cannot find module '../dist/cli/initializeCLI'
Require stack:
- /root/baler/bin/baler
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/baler/bin/baler:34:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)

I also try find similar file and directory in magento installed directory, but also without success

Can someone suggest, where I can find dist directory with related files

**Comment by DrewML** [comment]
Hey @vova3379,

Based on your `ls` output, it looks like you haven't run [the build](https://github.com/magento/baler/blob/43a47488f1fd87f9a87721dc64a3138a91843355/docs/ALPHA.md#build-from-source) yet. Can you try that and see if it fixes things for you?

**Comment by vova3379** [comment]
Hello @DrewML, 

thanks a lot for help
I see link to ALPHA.md
https://github.com/magento/baler/blob/43a47488f1fd87f9a87721dc64a3138a91843355/docs/ALPHA.md#build-from-source
but ignore it 

Issue fixed and closed.
