### ISSUE TITLE
npm sanity check failed with error code ELIFECYCLE

### ISSUE THREAD

**Issue by jiazhengshi** [magento/baler#35]
I tried to run **npm test** on a Macbook (node v10.16.0, npm 6.9.0), but failed. Part of the log is as follows. 

```
12 info lifecycle @magento/baler@0.0.1~format:check: Failed to exec format:check script
13 verbose stack Error: @magento/baler@0.0.1 format:check: `prettier --list-different $(head -1 prettier-globs)`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @magento/baler@0.0.1
```

**Comment by DrewML** [comment]
Thanks for the report @jiazhengshi. Can you send me the output of running the following 3 commands on their own, from the root of the repo?

```sh
ls node_modules/.bin
```

```sh
./node_modules/.bin/prettier
```

```sh
head -1 prettier-globs
```
